# https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
    name: scoutnet-secrets
data:
    apikey: {{ .Values.scoutnetCredentials.apiKey | b64enc }}
    pwd: {{ .Values.scoutnetCredentials.pwd | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: google-secrets
data:
    GDriveCreds: {{ .Values.googleCredentials | b64enc }}
